### ISSUE TITLE
Fix GH Action

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/r-without-statistics#32]
My GH action works inconsistently and I'm not quite sure why at this point. I can provide more context if helpful, but I think the best thing would be to have you just look at the most recent runs and see if you can figure out why it works sometimes and not others.

**Comment by tvroylandt** [comment]
It seems there was a problem with your renv installation. I try to fix it in https://github.com/rfortherestofus/r-without-statistics/actions/runs/5401145736/jobs/9810549510
